
name: Deploy GitHub Pages Test Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build
      
      - name: Check for the existence of the build directory
        run: |
          if [ ! -d "dist" ]; then
            echo "Build directory 'dist' does not exist. Exiting."
            exit 1
          fi
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          allow_empty_commit: true
          exclude_assets: ''