
name: Deploy GitHub Pages Test Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: create deployment directory
        run: |
          mkdir -p public
          mkdir -p public/dist

      - name: Copy files to deployment directory
        run: cp index.html public

      - name: Build the project
        run: tsc --project tsconfig.json --outDir public/dist
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          allow_empty_commit: true
          exclude_assets: ''